### ISSUE TITLE
how to load stylus plugins?

### ISSUE THREAD

**Issue by cliqer** [alexandesigner/lets#10]
How to use and where is the best place to load stylus plugins?
```
  import: [
    '~nib/index.styl',
    '~rupture/rupture/index.styl',
  ]
```

**Comment by alexandesigner** [comment]
Thanks for the question @gianniskarmas 

First of all it is important to point out that we are using the [vue-stylus](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-stylus#integrate-stylus-with-vue-single-file-components-for-meteor) plugin that is already embedded in the ``nib`` so you will not need install it, just import into your main file ``@import 'nib'`` and use it.

As for ``rupture``, yes, it is necessary to install later via npm (``meteor npm install --save-dev rupture``), after that you need to take it to the relative path of the ``node_modules``, import it and also use, below a small snippet.


``` stylus
// In file /imports/style/main.styl

@import 'nib'
@import 'nib/gradients'

// Take into consideration where your main file is or where you are importing the plugin
@import '../../../../node_modules/rupture/rupture/index.styl'

body
  fixed bottom right // nib
  background linear-gradient(top, white, black) // nib gradient
  +below(700px) // rupture sample
    background green
```

**Comment by alexandesigner** [comment]
**NOTE**: I'm considering replacing the package [standard-minifier-css](https://github.com/meteor/meteor/tree/devel/packages/standard-minifier-css) with [meteor-postcss](https://github.com/juliancwirko/meteor-postcss) consider making this change also to improve the import of files from node_modules .. would you import them just ``{}/node_modules/`` without worrying about the relative path. Other than that, I will also change the location of the ``/style`` folder to ``/startup/client``, would improve the organization and facilitate the integration of plugins and hot reload
