### ISSUE TITLE
Theme download

### ISSUE THREAD

**Issue by danishfred** [alexandesigner/lets#11]
Hi -  where do you get the download for the theme css files, i search the element page fruitless.
And please give me a tip for using your fantastic boilerplate in pure old fashion css - no pre- no post-processors -  no stylus just css and element-ui ( or are Element-ui default to Stylus - I miss some documentation

**Comment by alexandesigner** [comment]
> where do you get the download for the css files theme,

I'm just using an [Element UI theme generator](https://github.com/ElementUI/element-theme) and customizing some colors, shapes and sizes in the file [element-variables.scss](https://github.com/alexandesigner/lets/blob/master/boilerplate/src/element-variables.scss), for you to use, just install the global theme (``npm i -g element-theme``) and after installing the npm dependencies (``meteor npm i``). After in the command line run ``npm run generate:styles`` this will generate a set of files in a folder named ``src/theme``.

> please give me a tip for using your fantastic boilerplate in pure old fashion css - no pre- no post-processors - no stylus just css and element-ui ( or are Element-ui default to Stylus

Now if you do not want to use the stylus by default, you will need to install the package you prefer, scss, less or just css

First you remove the package ``akryum:vue-stylus@0.0.5`` then rename and edit the files that are in [src/imports/startup/styles](https://github.com/alexandesigner/lets/tree/master/boilerplate/src/imports/startup/client/styles) to the extension you want. **NOTE:** This will require a bit of manual labor

> I miss some documentation

It's true, I started to document, however much is still missing. But I am available if the doubt remains and if others arise.

**Comment by danishfred** [comment]
Hi and thanks for quick response.
Your answer actually fulfill my needs.
About the missing documentation - i didn't  wrote that to offend you - on the contrary I think you have done a great job - no actually I was referring to the ElementUI documentation
Thanks again

**Comment by alexandesigner** [comment]
I really appreciate that I have helped you.

Any questions or problems that arise, please do not hesitate to open a new question.

> About the missing documentation - i didn't wrote that to offend you - on the contrary I think you have done a great job - no actually I was referring to the ElementUI documentation

Dont worry.. I just emphasized that here we also need to improve the documentation, even to facilitate the integrations .. but in a way thank you very much and once again I'm happy to have helped.

**Comment by alexandesigner** [comment]
**Quickly note**: This boilerplate still needs many improvements, for example in my projects I am already using vuex, I have already implemented some tests as well and my desire is to add them to this boilerplate as well.
