### ISSUE TITLE
MIssing module

### ISSUE THREAD

**Issue by danishfred** [alexandesigner/lets#12]
Hi
When trying to run for the first time after downloading and updating all - I get this error

Unable to resolve some modules:

  "@babel/runtime/helpers/builtin/interopRequireDefault" in
/C/boil/boilerplate/src/imports/api/Documents/methods.js (os.windows.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime"

Ofcourse  I installed the babel/ runtime - but the same happens  again.

Any suggestions ???

**Comment by alexandesigner** [comment]
I had this problem when updating or using the latest version of ``@babel/runtime`` .. I recommend using a specific version to solve the ``"@babel/runtime": "^7.0.0-beta.54"``.

See https://github.com/meteor-vue/vue-meteor/issues/334
