### ISSUE TITLE
Documentation points to make install commands?

### ISSUE THREAD

**Issue by rrreche** [alexandesigner/lets#14]
I am a bit confused about the documentation. It is pointing to perform make commands but the project does not have any kind of makefile whatsoever, so the command is failing. Furthermore, every Meteor boilerplate project has always setup with the standard meteor commands and a little troubleshooting to address the classic dependency issues that arise. Am I doing something wrong?

**Comment by alexandesigner** [comment]
Thanks for the note, I even updated the .md files

Actually it was a bit outdated, before I used make just to optimize some commands, today I'm using npm scripts, feel free to use the commands directly as well ... 

> This is nothing more than a shortcut to some various commands.
