### ISSUE TITLE
"ReferenceError: window is not defined" for BackButton component

### ISSUE THREAD

**Issue by degger80** [alexandesigner/lets#8]
Open userEdit page or DocumentEditPage that contins this component and try refresh page. 
window is not defined on server side.

**Comment by alexandesigner** [comment]
@degger80 Thanks for the note and your contribution ..

I fix https://github.com/alexandesigner/lets/commit/bdd7e3bdfbe403432c18a29a1fb3b874640b962c  .. I'll close the issue, let me know if the problem continues.
